### ISSUE TITLE
<hr> color 在 ie11 下无效

### ISSUE THREAD

**Issue by mengshuaiyang** [yanxyz/ie-css-bugs#1]
使用<hr />标签
设置其color为white,在ie11下无效。
经测试，只在ie7及其一下有效，ie8、ie9、ie10、ie11均无效。

解决方案：通过设置border样式解决
这算bug吗?

**Comment by yanxyz** [comment]
不是 bug。`<hr>` 元素其实是一个 block 元素，故设置 color 是没有效果的，当然 IE<8 总是别具一格。可看下这篇文章 [How To Style &lt;hr&gt; with CSS](http://syntaxxx.com/how-to-style-hr-with-css/)

**Comment by mengshuaiyang** [comment]
谢谢，答疑。
